server:
  port: {SERVER_PORT}

app:
  cors:
    allowed-origins:
      - ${CORS_ORIGINS:http://localhost:4200}

spring:
  application:
    name: home-budget
  data:
    mongodb:
      uri: ${MONGO_APP_URL}
      database: ${MONGO_DATABASE}


management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

